// client/src/components/CreateList/index.svelte
<script lang="ts">
  import { InputCheckbox, InputText } from "..";
  import { useEffect } from "../../hooks";
  import ListItems from "./ListItems.svelte";
  import Recurring from "./Recurring.svelte";

  interface IOptions {
    recurring: boolean;
    recurType?: 'daily' | 'weekly' | null;
    recurDays?: string[] | null;
  }

  let listName: string = '';
  let options: IOptions = {
    recurring: false
  }
  let listItems: string[] = [];

  let isRecurring: boolean;
  $: isRecurring = !!options?.recurring;

  let nameInput: HTMLInputElement | null;

  const listNameInput = (e) => {
    listName = e.detail.value;
  }

  const setOptions = (property: string) => (e) => {
    options[property] = e.detail.value;
  }

  const setListItems = (e) => {
    listItems = e.detail.value;
  }

  const handleSubmit = () => {
    console.log(`
      listName: ${listName}
      listItems: ${listItems.join(', ')}
    `);
  }

  useEffect(() => {
    if (!options.recurring) {
      options.recurType = null;
      options.recurDays = null;
    }
  }, () => [options]);
  
  useEffect(() => {
    nameInput?.focus();
  }, () => [nameInput]);
  
</script>

<section>
  <h2>Create a new list</h2>

  <div class="big">
    <InputText
      placeholder="My list"
      label="Name this list:"
      name="listname"
      bind:value={listName}
      on:input={listNameInput}
      createRef={(el) => { nameInput = el }}
    />
  </div>

  <div>
    <InputCheckbox label="Recurring?" name="recurring" bind:checked={options.recurring} />
    {#if isRecurring}
      <Recurring on:selectType={setOptions('recurType')} on:selectDays={setOptions('recurDays')} />
    {/if}
  </div>

  <div>
    <ListItems on:update={setListItems} />
  </div>

  <button class="block" style="margin-top: 1rem" on:click={handleSubmit}>Save</button>
</section>

<style>
  h2 {
    margin-bottom: 0;
  }
  section > * {
    margin-bottom: 1.5rem;
  }
  .big {
    font-size: 1.2rem;
  }
</style>

<!-- 
  - allow rearrange and delete tasks
  - clear all
  - list titles
  - conditions for recurring
 -->

// client/src/app/pages/new/create-list.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'page-create-list',
  templateUrl: './create-list.component.html'
})

export class CreateListComponent {
  listName = '';
  options: {
    recurring: 'never' | 'daily' | 'weekly',
    details?: string
  } = {
    recurring: 'never'
  }
  listItems: string[] = [];

  setListName = (e: any) => {
    this.listName = e.target.value;
  }

  handleSubmit = () => {
    console.log(`
listName: ${this.listName}
options.recurring: ${this.options.recurring}
options.details: ${this.options.details}
listItems: ${this.listItems.join(', ')}
`)
  }
}
<style>
  :host > * + * {
    margin-top: 1.5rem;
  }
  :host > button.block {
    margin-top: 2.5rem;
  }
  .name {
    font-size: 1.2rem;
  }
</style>

<h2>create new list</h2>

<div class="name">
  <label for="listname">Name this list:</label>
  <input autofocus autocomplete="off" type="text" name="listname" placeholder="My list" (change)="setListName($event)" />
</div>

<div>
  <recurring [options]="options"></recurring>
</div>

<div>
  <list-items [listItems]="listItems"></list-items>
</div>

<button class="block" (click)="handleSubmit()">Save</button>
